### ISSUE TITLE
SwiftUI previews do not work when using SwiftyMocky with iOS

### ISSUE THREAD

**Issue by andlang** [MakeAWishFoundation/SwiftyMocky#231] opened 2019-12-19 08:02 UTC
I included SwiftyMocky (3.4.0) in my iOS project with the Swift Package Manager. When I try to build the SwiftUI preview, the build fails in the dependency ShellOut with “Class Process is unknown” (it’s only available in macOS) . It seems, that the preview wants to build all of the dependencies, no matter what platform is supported. I could only solve the issue in removing all of the dependencies (for the SwiftyMockyCLI).

Is it possible, to make two packages? One for SwiftyMocky and one for SwiftyMockyCLI? In that way, there wouldn’t be an issue with the SwiftUI preview.

Maybe it will also be solved with: https://github.com/apple/swift-evolution/blob/master/proposals/0273-swiftpm-conditional-target-dependencies.md

**Comment by pballart** [comment] 2020-02-08 18:05
Same issue here. How did you manage to remove the SwiftyMockyCLI dependencies but still keep SwiftyMocky running for the tests?

**Comment by amichnia** [comment] 2020-02-12 11:06
Hi guys. I will look into that over the weekend. In general, I think the problem is that we used originally SPM for CLI tool, which of course would not work in test targets.

**Comment by andlang** [comment] 2020-02-12 11:58
@pballart I still use the legacy way with sourcery and a yaml config (https://github.com/MakeAWishFoundation/SwiftyMocky/blob/master/guides/Legacy.md). Therefore I could remove all targets from `Package.swift` except “SwiftyMocky”. But that was just a quick fix.

**Comment by glyuck** [comment] 2020-03-12 08:17
I've faced the same issue. As a workaround, I install SwiftyMocky runtime via Carthage and the SwiftyMockyCLI via Mint.

**Comment by Przemyslaw-Wosko** [comment] 2020-03-14 00:42
Since we want to be ready for SwiftUI ASAP, i will try to help @andrzejmichnia resolve this issue

**Comment by kzietek** [comment] 2020-03-19 20:18
For those using SPM I made a workaround by removing all things related to CLI from `Package.swift`:
1. File > Swift Packages > Reset package caches
2. Add `git@github.com:kzietek/SwiftyMocky.git` with branch `NoCLI`. 
3. Be sure to select your test target when prompted.

**Comment by pballart** [comment] 2020-03-22 12:47
I just tried it and it works fine! 🎉

**Comment by g-amichnia** [comment] 2020-06-23 17:53
Should be fixed in 4.0.0

**Closed by g-amichnia** 2020-06-23 17:53 UTC
Labels: bug

**Comment by chkpnt** [comment] 2020-07-11 16:46
I just updated SPM to the latest commit of SwiftyMocky and can confirm: SwiftUI-Preview works :-)
Thank you!
