### ISSUE TITLE
Setting nil on a mocked property causes a fallback to the mocked value instead

### ISSUE THREAD

**Issue by wvteijlingen** [MakeAWishFoundation/SwiftyMocky#267] opened 2020-10-12 09:32 UTC
Given the code below, I would expect both the asserts to succeed. However, the second `XCTAssertNil` fails because SwiftyMocky uses the nil coalescing operator in the mocked getter.

```swift
let mockedDate = Date()
Given(someObject, .someProperty(getter: mockedDate))
XCTAssertNotNil(someObject.someProperty) // Succeeds
someObject.someProperty = nil
XCTAssertNil(someObject.someProperty) // Fails, this returns the mocked date instead of nil
```

The nil coalescing getter causes a fallback to the initially mocked value instead of returning the actual value that was explicitly set (which is `nil`).

```swift
// This is in the generated mock getter:
return __p_someProperty ?? optionalGivenGetterValue(.p_someProperty_get, "SomeObjectProtocolMock - stub value for someProperty was not defined")
```

In this example you could work around this by using `Verify`, but since the generated mock contains the ability to store a value (`__p_someProperty`), I would consider this behaviour a bug or at least a nasty edge case that should be documented.

One way to solve this would be to remove the nil coalescing operator, and instead use some other flagging system to decide whether to return the initially mocked value, or the explicitly set value.

**Comment by g-amichnia** [comment] 2021-01-22 17:02
Hi, so this topic was under discussion for a long time, and I don't have an answer I am 100% sure is correct.

In general, what you described as correct behaviour, was initial implementation. But it means that mocks are then less "mocks", and more like implementation, with this implicit assumption, that when you "set", get should return you value you've set. This is not always the case.

We decided to go with "as dumb mock as possible", so you need to use `Given(.property, willReturn: value)` to specify returned value. There is no implicit "if you call setter with value, getter would return it", since this results in mixing up mock setup code with actual invocations to it, making using `Verify` for setters a lot harder.

And you can still achieve the behaviour you described, using `Perform` and `Given` in its closure.

So, I am closing it for now, as this is intended behaviour, but feel free to continue discussion if you see any strong arguments for/against that.

**Closed by g-amichnia** 2021-01-22 17:02 UTC
Labels: bug, question
