### ISSUE TITLE
No such module 'Commander'

### ISSUE THREAD

**Issue by nskonieczko** [MakeAWishFoundation/SwiftyMocky#245] opened 2020-04-06 21:52 UTC
tried cocoapods, SPM, and carthage all say the same issue.

**Comment by Przemyslaw-Wosko** [comment] 2020-04-09 21:14
Could you share little bit more about this issue? i can't reproduce it.

**Comment by nskonieczko** [comment] 2020-04-09 21:16
So I was able to figure it out ... well kind of. When running the setup cli
it started to add other imports and got confused. I simply deleted a few of
the imports and it work :)

By the way I really love this library. I would love to know what the plans
are for the future. Would also love to contribute if possible.

Thanks for reaching out

Nick

**Comment by Przemyslaw-Wosko** [comment] 2020-04-09 21:19
@nskonieczko Thanks for reply, i'm closing the issue.

And btw- regarding SwiftyMockyCLI, on scale 0-10, how this tool helped you? 

we have a lot of issues because of this tool, especially config stuff, so i'm thinking about removing that from main repository, looking forward for review :)

**Closed by Przemyslaw-Wosko** 2020-04-09 21:19 UTC

**Comment by nskonieczko** [comment] 2020-04-10 00:10
So i tested the cli tool on a brand new project. Works perfectly, using
currently on a very complex project with tons of dependencies, and it
broke. So I think I would need more time to really evaluate how well
helpful it is. That said. I wouldn’t know what to do otherwise. Also having
the config file to add the imports is really nice.

Nick
