### ISSUE TITLE
SwiftyMocky doesn't work after updating to Xcode 13.3

### ISSUE THREAD

**Issue by soundbites** [MakeAWishFoundation/SwiftyMocky#306] opened 2022-03-17 08:49 UTC
When updating to the latest Xcode version 13.3 SwiftyMocky generate fails with the following message;

```
Unable to parse error The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax
error: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax
```

I guess it is from a dependency that hasn't been updated yet. Anything we can do? except downgrade to a previous Xcode version?

**Comment by Smponias** [comment] 2022-03-17 16:58
Even after downgrading to Xcode 13.2.1 it doesn't work for me.

**Comment by StilianosTzouvaras** [comment] 2022-03-21 11:23
Any news on this issue?

**Comment by bolo992** [comment] 2022-03-21 13:35
It doesn't work for me as well, Xcode 13.3. I tried to uninstall and install again using Xcode 13.3 command line tools but it doesn't work still.

**Comment by StilianosTzouvaras** [comment] 2022-03-21 13:40
One solution without downgrading  XCODE is to install sourcery via homebrew brew install sourcery and then use sourceryCommand inside the template and set it to sourcery

sourceryCommand: sourcery

**Comment by ohitsdaniel** [comment] 2022-03-24 13:17
For all Mint users, install Sourcery 1.7.0 (`mint install krzysztofzablocki/Sourcery@1.7.0`) and then define `sourceryCommand: mint run krzysztofzablocki/Sourcery@1.7.0 sourcery` in your Mockfile.

**Comment by NSCabezon** [comment] 2022-03-25 12:26
> For all Mint users, install Sourcery 1.7.0 (`mint install krzysztofzablocki/Sourcery@1.7.0`) and then define `sourceryCommand: mint run krzysztofzablocki/Sourcery@1.7.0 sourcery` in your Mockfile.

After installing and specifying it on the Mockfile I still get the `_InternalSwiftSyntaxParser` error any idea why?

**Comment by bolo992** [comment] 2022-03-26 15:08
Well i managed to finally make it works. Follow next steps:
1. First be sure that you installed the latest sourcery: **brew install sourcery**

2. Second remove the deprecated collections.json using next command:
**rm ~/.swiftpm/config/collections.json**

3. Add in Mockfile:
**sourceryCommand: sourcery**

So when you execute **swiftymocky generate** command it should work.

**Comment by krzysztofzablocki** [comment] 2022-03-28 09:39
Mint wasn't supported before (will be in next release) since Sourcery had to rewrite rPath for SwiftSyntax dylib, Mint doesn't do that as it only builds with SPM and so you end up with whatever the default Xcode location dylib is, which might not be compatibile with what Sourcery used as a library. 

We are now switching to static linking for SwiftSyntax which should resolve this issue altogether

**Comment by pchmelar** [comment] 2022-03-29 07:46
@krzysztofzablocki Thanks for the 1.8.0 release! I can confirm that bumping Sourcery to 1.8.0 in Mintfile and then using `sourceryCommand: mint run sourcery` in Mockfile works as expected 🎉

**Comment by timstudt** [comment] 2022-03-29 10:22
> @krzysztofzablocki Thanks for the 1.8.0 release! I can confirm that bumping Sourcery to 1.8.0 in Mintfile and then using `sourceryCommand: mint run sourcery` in Mockfile works as expected 🎉

with `sourceryCommand: mint run sourcery` swiftymocky installs the latest Sourcery version using mint. Meaning you don't need to add Sourcery to any Mintfile... or use Mintfile to install Sourcery and point `sourceryCommand:` to where  you installed it.

**Closed** 2022-04-21 19:51 UTC
